# SwiftLint Configuration for LiquidAuthSDK
# https://github.com/realm/SwiftLint

# Paths to include during linting
included:
  - Sources
  - Tests

# Paths to ignore during linting
excluded:
  - .build
  - Package.swift
  - .swiftpm

# Rules to disable
disabled_rules:
  - trailing_whitespace # Let SwiftFormat handle this
  - vertical_whitespace # Let SwiftFormat handle this
  - file_header # Files already have correct headers
  - function_body_length # Ignore for now
  - type_body_length # Ignore for now

# Rules to enable
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Customizable rules
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_parameter_count:
  warning: 8
  error: 10

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - url
    - uri
    - M
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - S0
    - S1
    - NODELY_TURN_USERNAME
    - NODELY_TURN_CREDENTIAL

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 60
  excluded:
    - SHA512_256

# Custom rules for SDK-specific patterns
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use Logger instead of print statements"
    severity: warning

  proper_logger:
    name: "Proper Logger Usage"
    regex: "NSLog\\("
    message: "Use Logger.debug/info/error instead of NSLog directly"
    severity: warning
    excluded: "Logger.swift"

# Reporter configuration
reporter: "xcode" # Can be: xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown

# Analyzer rules (for more advanced static analysis)
analyzer_rules:
  - unused_import
  - unused_declaration
